apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: database
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mongodb
        image: mongo
        volumeMounts:
        - name: apidata
          mountPath: "/data"
  volumeClaimTemplates:
  - metadata:
      name: apiata
    spec:
      accessModes: 
      - ReadWriteOnce 
      resources:
        requests:
          storage: 1Gi
